### ISSUE TITLE
The Website

### ISSUE THREAD

**Issue by EhWhoAmI** [EhWhoAmI/Monster-Quest#4]
The website needs to be done. I will upload it soon.

**Comment by EhWhoAmI** [comment]
The Website has horrible interfacing issues. The colors look horrible, so please fix.

**Comment by EhWhoAmI** [comment]
It's even worst now, because I deleted it.

**Comment by Flamentix** [comment]
I can help create an HTML + CSS website if design is all you care about.

**Comment by EhWhoAmI** [comment]
No thx.

**Comment by EhWhoAmI** [comment]
Gave up on this project half a year ago.
